### ISSUE TITLE
BLE notifications does not work on HexiWear

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-examples#205] opened 2016-09-12 12:26 UTC
BLE notifications does not work for some characteristics, e.g. the mode characteristic.

But notifications works for battery characteristic, for example.

**Comment by mikaelkindborg** [comment] 2016-09-12 12:56
app.startNotifications = function() {
	// but first, read static data.
	app.status("Reading data...");
	app.readCharacteristic(app.INFO_SERVICE, app.INFO_MANUFACTURER, "manufacturer", evothings.ble.fromUtf8);
	app.readCharacteristic(app.INFO_SERVICE, app.INFO_FIRMWARE, "firmware", evothings.ble.fromUtf8);
	app.readCharacteristic(app.INFO_SERVICE, app.INFO_SERIAL, "serial", app.convertHexData);
	app.readCharacteristic(app.BATTERY_SERVICE, app.BATTERY_CHARACTERISTIC, "battery", app.convert8bitPercentageData);
	app.readCharacteristic(app.MODE_SERVICE, app.MODE_CHARACTERISTIC, "mode", app.convertModeData);

	// OK, now we can do notifications.
	app.enableNotification(app.BATTERY_SERVICE, app.BATTERY_CHARACTERISTIC, "battery", app.convert8bitPercentageData);
	app.enableNotification(app.MODE_SERVICE, app.MODE_CHARACTERISTIC, "mode", app.convertModeData);

	// or not. These services do not support BLE notification, even though you would expect it.
	// Polling is possible, but quite inefficient by comparison.
	// app.enableNotification(app.MOTION_SERVICE, app.MOTION_ACCELEROMETER, "accel", app.convert3x16bitData);
	//app.enableNotification(app.MOTION_SERVICE, app.MOTION_GYRO, "gyro", app.convert3x16bitData);
	//app.enableNotification(app.MOTION_SERVICE, app.MOTION_MAGNET, "magnet", app.convert3x16bitData);

	// Let's try polling instead.
	app.timer = window.setInterval(app.poll, 1000);
}

app.poll = function() {
	app.readCharacteristic(app.MOTION_SERVICE, app.MOTION_ACCELEROMETER, "accel", app.convert3x16bitData);
	app.readCharacteristic(app.MOTION_SERVICE, app.MOTION_GYRO, "gyro", app.convert3x16bitData);
	app.readCharacteristic(app.MOTION_SERVICE, app.MOTION_MAGNET, "magnet", app.convert3x16bitData);

	app.readCharacteristic(app.WEATHER_SERVICE, app.WEATHER_AMBIENT, "ambient", app.convert8bitPercentageData);
	app.readCharacteristic(app.WEATHER_SERVICE, app.WEATHER_TEMPERATURE, "temperature", app.convertTemperatureData);
	app.readCharacteristic(app.WEATHER_SERVICE, app.WEATHER_HUMIDITY, "humidity", app.convertHumidityData);
	app.readCharacteristic(app.WEATHER_SERVICE, app.WEATHER_PRESSURE, "pressure", app.convertPressureData);

	app.readCharacteristic(app.HEALTH_SERVICE, app.HEALTH_HEART, "heart", app.convertHeartData);
	app.readCharacteristic(app.HEALTH_SERVICE, app.HEALTH_STEPS, "steps", app.convert16bitUnsignedData);
	app.readCharacteristic(app.HEALTH_SERVICE, app.HEALTH_ACTIVITY, "activity", app.convert16bitUnsignedData);
}

**Comment by ghost** [comment] 2016-11-24 10:01
Turns out this is by design, notifications are not available for all characteristics. Closing issue.

**Closed by ghost** 2016-11-24 10:01 UTC
